package tui

import (
	"fmt"
	"strings"

	"charm.land/lipgloss/v2"
)

func (state *editor) clauseInsight(width int) string {
	if state.active < 0 || state.active >= len(state.lines) {
		return mutedStyle.Render("Select a clause to inspect its role.")
	}
	line := strings.TrimSpace(state.lines[state.active])
	if line == "" {
		return mutedStyle.Render("Type a source or option. Each line stays an ordinary CLI clause.")
	}
	if !strings.HasPrefix(line, "-") {
		name := highlightReference(line, state.lines, state.config.Registry)
		return inspectorBlock(width,
			"PRIMARY TELEMETRY", name,
			"The bare source is the default control for every -m clause that omits CONTROL:.",
			"Add another source inline: -m gpu.usage:TARGET=MAP",
		)
	}

	option, value, hasValue := strings.Cut(line, " ")
	if !hasValue {
		return mutedStyle.Render("Choose a completion to finish this clause.")
	}
	switch option {
	case "-s":
		if synth, ok := synthAtLine(state.lines, state.active); ok {
			id := semanticStyleFor(synthIdentity(synth.ID), state.lines, state.config.Registry).Render(synth.ID)
			output := highlightReference("syn."+synth.ID+".out", state.lines, state.config.Registry)
			return inspectorBlock(width,
				"SYNTH NODE", fmt.Sprintf("%s  %s", id, mutedStyle.Render(string(synth.Type))),
				"Values inside -s are fixed base parameters; telemetry is connected with -m.",
				"Audio-rate signal: "+output,
			)
		}
	case "-m":
		return state.modulationInsight(value, width)
	case "--range":
		control, valueRange, explicit := strings.Cut(value, "=")
		if !explicit {
			control, valueRange = primarySource(state.lines), value
		}
		return inspectorBlock(width,
			"INPUT RANGE", highlightReference(control, state.lines, state.config.Registry),
			"Normalizes this control from "+valueRange+" before mappings are applied.",
			"Omitting CONTROL= means the primary telemetry source.",
		)
	}
	return inspectorBlock(width,
		"CLAUSE", line,
		"This clause uses the ordinary STASH command language.",
		"Use -m [CONTROL:]TARGET=MAP to create a route.",
	)
}

func (state *editor) modulationInsight(value string, width int) string {
	left, mapping, hasMap := strings.Cut(value, "=")
	if !hasMap {
		mapping = "MAP"
	}
	control, target, explicitControl := strings.Cut(left, ":")
	if !explicitControl {
		target = control
		control = primarySource(state.lines)
	}
	controlLabel := highlightReference(control, state.lines, state.config.Registry)
	resolvedTarget := resolvedTargetReference(target, state.lines)
	targetLabel := highlightTargetReference(resolvedTarget, state.lines, state.config.Registry)
	rate := "CONTROL-RATE MAP"
	explanation := "Telemetry maps values into a parameter; it does not become an audio signal."
	if strings.HasPrefix(control, "syn.") && strings.HasSuffix(control, ".out") {
		rate = "AUDIO-RATE ROUTE"
		explanation = "Only syn.ID.out is an audio-rate signal; the target must support audio-rate modulation."
	} else if strings.HasPrefix(control, "rhythm.") {
		rate = "RHYTHM CONTROL MAP"
		explanation = "Rhythm controls are generated by -r and mapped like telemetry controls."
	} else if !explicitControl {
		controlLabel += mutedStyle.Render("  (primary shorthand)")
	}
	return inspectorBlock(width,
		rate, controlLabel+"  →  "+targetLabel,
		"Map: "+mapping,
		explanation,
	)
}

func resolvedTargetReference(target string, lines []string) string {
	synths := partialSynths(lines)
	if len(synths) == 0 {
		return target
	}
	latest := synths[len(synths)-1].ID
	if strings.HasPrefix(target, "syn.") {
		rest := strings.TrimPrefix(target, "syn.")
		first, _, hasDot := strings.Cut(rest, ".")
		if !hasDot || !hasSynthID(lines, first) {
			return "syn." + latest + "." + rest
		}
		return target
	}
	for _, legacy := range []string{"freq", "gain", "pan", "gate"} {
		if target == legacy {
			return "syn." + latest + "." + target
		}
	}
	return target
}

func inspectorBlock(width int, role, route string, details ...string) string {
	var body strings.Builder
	body.WriteString(labelStyle.Render(role))
	body.WriteByte('\n')
	body.WriteString(lipgloss.NewStyle().Width(width).Render(route))
	for _, detail := range details {
		if strings.TrimSpace(detail) == "" {
			continue
		}
		body.WriteString("\n\n")
		body.WriteString(mutedStyle.Width(width).Render(detail))
	}
	return body.String()
}

func primarySource(lines []string) string {
	for _, raw := range lines {
		line := strings.TrimSpace(raw)
		if line != "" && !strings.HasPrefix(line, "-") {
			return line
		}
	}
	return "primary source"
}
